# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 122c2de78747a7b9bf606bb1f79d507e0610b75108d1bea15b1b4f7601b3c96fac7023fe5762d3268bf0b46c21e9bbf0cd9280eddee21a19669310c2f375350b

test:
  secret_key_base: b551eee95ffdcec468ae9d163f7621e9e731ec49aab1a9ca8bcf4d11d993c52140aafb688623180d4e0b67055df5ab49668a790df949d7f9d339d3803a256c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
